# Generated by Django 2.2.10 on 2020-10-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_accounting_card', models.CharField(help_text='Номер карточки учета животного', max_length=20, primary_key=True, serialize=False, verbose_name='Карточка учета животного')),
                ('animal_kind', models.CharField(choices=[('c', 'КОТ'), ('d', 'СОБАКА')], help_text='Вид животного', max_length=1, verbose_name='Вид животного')),
                ('animal_birth_date', models.DateTimeField(help_text='Возраст, дата рождения', verbose_name='Возраст, дата рождения')),
                ('animal_weight', models.FloatField(help_text='Вес', max_length=5, verbose_name='Вес')),
                ('animal_name', models.CharField(default='без клички', help_text='Кличка', max_length=20, verbose_name='Кличка')),
                ('animal_sex', models.CharField(max_length=1)),
            ],
        ),
    ]
