# Generated by Django 2.2.10 on 2020-10-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2b_api', '0002_auto_20201031_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='shelter',
        ),
        migrations.AddField(
            model_name='shelter',
            name='animals',
            field=models.ManyToManyField(help_text='Животные', null=True, to='s2b_api.Animal', verbose_name='Животные'),
        ),
    ]
