# Generated by Django 2.2.10 on 2020-10-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2b_api', '0004_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, help_text='Имя работника', max_length=30, null=True, verbose_name='Имя работника'),
        ),
    ]
