# Generated by Django 2.2.10 on 2020-10-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2b_api', '0006_auto_20201031_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='animals',
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(help_text='Приют', null=True, on_delete=django.db.models.deletion.CASCADE, to='s2b_api.Shelter', verbose_name='Приют'),
        ),
    ]
