# Generated by Django 2.2.10 on 2020-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2b_api', '0007_auto_20201031_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(help_text='Возраст, дата рождения', verbose_name='Возраст, дата рождения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='entrance_act_date',
            field=models.CharField(help_text='Акт о поступлении. Дата', max_length=25, null=True, verbose_name='Акт о поступлении. Дата'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='leaving_act_date',
            field=models.DateField(blank=True, help_text='Дата выбытия', null=True, verbose_name='Дата выбытия'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='medical_checkup_date',
            field=models.DateField(blank=True, help_text='Дата медосмотра', null=True, verbose_name='Дата медосмотра'),
        ),
    ]
