# Generated by Django 2.2.10 on 2020-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2b_api', '0008_auto_20201031_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='catching_act_date',
            field=models.CharField(blank=True, help_text='Дата отлова', max_length=15, null=True, verbose_name='Дата отлова'),
        ),
    ]
