# Generated by Django 2.2.10 on 2020-11-01 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s2b_api', '0013_auto_20201031_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, help_text='Дата регистрации заявки')),
                ('quiz', models.TextField(blank=True, help_text='Ответы на вопросы', max_length=500)),
                ('status', models.CharField(choices=[('r', 'Заявка на рассмотрении'), ('d', 'Заявка отклонена'), ('a', 'Заявка одобрена')], default='r', help_text='Статус заявки', max_length=1)),
                ('animal', models.OneToOneField(help_text='На какое животное сделана заявка', on_delete=django.db.models.deletion.CASCADE, to='s2b_api.Animal')),
                ('user', models.ForeignKey(help_text='Пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
